### ISSUE TITLE
Provide API to access its shadow DOM from stanza

### ISSUE THREAD

**Issue by darashi** [togostanza/ts#30]

**Comment by darashi** [comment]
How?

1. Export `stanza.element`
2. Export `stanza.shadowRoot`
3. Provide `stanza.select(selector)`; Then what should be returned? Is the name appropriate?
  1. `$(selector, element.shadowRoot)`
  2. `element.shadowRoot.querySelectorAll(selector)`
  3. `element.shadowRoot.querySelector(selector)`
4. Combination of above

**Comment by ursm** [comment]
5. Provide `stanza.$()`. This is similar to Ember.js.

**Comment by darashi** [comment]
Does `stanza.$()` return a jQuery object or something else?

**Comment by darashi** [comment]
Tried to implement `stanza.$()` with jQuery: https://github.com/togostanza/ts/tree/stanza-doller

**Comment by darashi** [comment]
done by #33

**Comment by darashi** [comment]
```
3-iii: stanza.select(selector)
3-ii: stanza.selectAll(selector)
```

とするのはどうか？

**Comment by darashi** [comment]
Revert `stanza.$()` and implement `stanza.select()`, `stanza.selectAll()` and `stana.root()`

**Comment by darashi** [comment]
b76ec998441ad2eaf38775a6db23fd862c8fc826
