### ISSUE TITLE
Error on using multiple stanzas at the same time

### ISSUE THREAD

**Issue by kokubo** [togostanza/ts#54]
I had an issue using more than one stanza in the same HTML file.
The version I've used is v0.0.13.

Let's say I have 2 stanzas `togostanza-sample1` and `togostanza-sample2`.
In an HTML file, I wrote like the following:
```html
<html>
<head>
  <script src="https://cdn.jsdelivr.net/npm/@webcomponents/webcomponentsjs@1.3.0/webcomponents-loader.js" crossorigin></script>
  <link rel="import" href="https://example.com/stanza/sample1/">
  <link rel="import" href="https://example.com/stanza/sample2/">
</head>
<body>
  <togostanza-sample1></togostanza-sample1>
  <togostanza-sample2></togostanza-sample2>
</body>
</html>
```

After loading the HTML file on my browser (Chrome), it gives me the following error:
```
Uncaught SyntaxError: Identifier 'descriptor' has already been declared
    at (index):4
```

This happens because both stanzas have the same variable `descriptor` in the global scope which was generated from `ts build` command.
It looks like each stanza need to have its own JavaScript scope.

**Comment by kokubo** [comment]
I confirm that this wasn't the issue on v0.0.12.

**Comment by ursm** [comment]
There was a problem just as you said. We released a fixed package, so please try it. Thank you for notifying us.
https://github.com/togostanza/ts/releases/tag/v0.0.14

**Comment by kokubo** [comment]
The new version worked perfectly!
Thank you so much for fixing the problem so quickly.
